### PR TITLE
fix null return when fields adress are empty

### PR DESCRIPTION
**Pull request by cyberbobjr**

### CODE REVIEW

**Comment by dereuromark** [comment]
Is there maybe a test case for this?
What is the issue here - what does it fix?

**Comment by cyberbobjr** [comment]
sorry i didn't complete the ref issue :/

**Comment by dereuromark** [comment]
@ping
I need at least some test case or "description" of how to reproduce the issue in order to confirm the fix.

**Comment by cyberbobjr** [comment]
Hi Dereuromark,
you can test a save cancelled with this :
- create a "Shop" Table with 3 fields : address (varchar(255)), city (varchar(255)), zipcode (varchar(255))
- attach behavior to the model :
```
        $this->addBehavior('Geo.Geocoder', ['locale'  => 'FR',
                                            'apiKey'  => 'abcdefgh',
                                            'ssl'     => TRUE,
                                            'address' => ['address',
                                                          'zipcode',
                                                          'city']]);
```
- made a new entity 
```
$shop = $this->Shops->newEntity(['address'=>'','city'=>'','zipcode'=>'']);
$shop = $this->Shops->save($shop);
```
The $shop will contain the entity, but the record is not saved in the database.

**Comment by cyberbobjr** [comment]
Hi, 
any news please ?

**Comment by dereuromark** [comment]
I think it is better to not go into _execute() here in the first place then.

**Pull request closed without merging**
